### ISSUE TITLE
Please add a config

### ISSUE THREAD

**Issue by PeterLangendorf** [iPortalTeam/PortalGun#4]
### According to your testing, does the issue occur with ONLY Portal Gun mod and Immersive Portals mod and Farbic API?

Yes

### Describe the issue

This is not an issue - but you don't have a discord so I guess I'll post it here.

Please add a config for settings such as a list of blocks that portals cannot be placed on.
I am trying to recreate some portal features and I have to make non-portalable panels out of leaves right now.
Additionally, a command to spawn portals would be very convenient. If this is not doable due to it being impossible to code, that would be very sad.
Another option that would be nice is one to change how flings work. I don't like how you can fall from 5 blocks and get 75% of the velocity you'd get from 75 blocks. An options such as fling_scaling in the config that would make you fling further would be very helpful.
Thank you.

### Post the log here

```shell
Dunno what to put here...
Please make a discord
```

**Comment by SalTeyJek004** [comment]
I saw this from the discord : https://discord.gg/BZxgURK

**Comment by qouteall** [comment]
The discord is the same as Immersive Portals: https://discord.gg/BZxgURK

I am going to make it controlled by the data in portal gun item, so that each portal gun can work on different blocks.

About commands: ImmPtl have a lot of command https://qouteall.fun/immptl/wiki/Commands-Reference.html but the commands cannot create portal gun's unique type of portal. I am considering adding it.

About velocity: you can increase motionAffinity by `/portal nbt {motionAffinity:2.0}` and it will accelerate the player when touching. However it will be reset if the portal gets recreated.

**Comment by PeterLangendorf** [comment]
Got it. Thanks!
